In [12]:
import torch

In [2]:
d_model = 6
sequence_length = 10

#positional encoding

In [3]:
even_i = torch.arange(0, d_model, 2).float()
even_i

tensor([0., 2., 4.])

In [4]:
odd_i = torch.arange(1, d_model, 2).float()
odd_i

tensor([1., 3., 5.])

In [5]:
even_denomenater = torch.pow(10000, even_i / d_model)
even_denomenater

tensor([  1.0000,  21.5443, 464.1590])

In [6]:
odd_denomenater = torch.pow(10000, odd_i / d_model)
odd_denomenater

tensor([   4.6416,  100.0000, 2154.4343])

In [7]:
positions = torch.arange(sequence_length, dtype=torch.float).reshape(sequence_length, 1)
positions

tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [8]:
even_pe = torch.sin(positions / even_denomenater)
even_pe

tensor([[ 0.0000,  0.0000,  0.0000],
        [ 0.8415,  0.0464,  0.0022],
        [ 0.9093,  0.0927,  0.0043],
        [ 0.1411,  0.1388,  0.0065],
        [-0.7568,  0.1846,  0.0086],
        [-0.9589,  0.2300,  0.0108],
        [-0.2794,  0.2749,  0.0129],
        [ 0.6570,  0.3192,  0.0151],
        [ 0.9894,  0.3629,  0.0172],
        [ 0.4121,  0.4057,  0.0194]])

In [9]:
odd_pe = torch.cos(positions / odd_denomenater)
odd_pe

tensor([[ 1.0000,  1.0000,  1.0000],
        [ 0.9769,  0.9999,  1.0000],
        [ 0.9086,  0.9998,  1.0000],
        [ 0.7983,  0.9996,  1.0000],
        [ 0.6511,  0.9992,  1.0000],
        [ 0.4738,  0.9988,  1.0000],
        [ 0.2746,  0.9982,  1.0000],
        [ 0.0627,  0.9976,  1.0000],
        [-0.1522,  0.9968,  1.0000],
        [-0.3599,  0.9960,  1.0000]])

In [10]:
PE = torch.stack([even_pe, odd_pe], dim=2)
PE

tensor([[[ 0.0000,  1.0000],
         [ 0.0000,  1.0000],
         [ 0.0000,  1.0000]],

        [[ 0.8415,  0.9769],
         [ 0.0464,  0.9999],
         [ 0.0022,  1.0000]],

        [[ 0.9093,  0.9086],
         [ 0.0927,  0.9998],
         [ 0.0043,  1.0000]],

        [[ 0.1411,  0.7983],
         [ 0.1388,  0.9996],
         [ 0.0065,  1.0000]],

        [[-0.7568,  0.6511],
         [ 0.1846,  0.9992],
         [ 0.0086,  1.0000]],

        [[-0.9589,  0.4738],
         [ 0.2300,  0.9988],
         [ 0.0108,  1.0000]],

        [[-0.2794,  0.2746],
         [ 0.2749,  0.9982],
         [ 0.0129,  1.0000]],

        [[ 0.6570,  0.0627],
         [ 0.3192,  0.9976],
         [ 0.0151,  1.0000]],

        [[ 0.9894, -0.1522],
         [ 0.3629,  0.9968],
         [ 0.0172,  1.0000]],

        [[ 0.4121, -0.3599],
         [ 0.4057,  0.9960],
         [ 0.0194,  1.0000]]])

In [11]:
PE = torch.flatten(PE,start_dim=1,end_dim=-1)
PE

tensor([[ 0.0000,  1.0000,  0.0000,  1.0000,  0.0000,  1.0000],
        [ 0.8415,  0.9769,  0.0464,  0.9999,  0.0022,  1.0000],
        [ 0.9093,  0.9086,  0.0927,  0.9998,  0.0043,  1.0000],
        [ 0.1411,  0.7983,  0.1388,  0.9996,  0.0065,  1.0000],
        [-0.7568,  0.6511,  0.1846,  0.9992,  0.0086,  1.0000],
        [-0.9589,  0.4738,  0.2300,  0.9988,  0.0108,  1.0000],
        [-0.2794,  0.2746,  0.2749,  0.9982,  0.0129,  1.0000],
        [ 0.6570,  0.0627,  0.3192,  0.9976,  0.0151,  1.0000],
        [ 0.9894, -0.1522,  0.3629,  0.9968,  0.0172,  1.0000],
        [ 0.4121, -0.3599,  0.4057,  0.9960,  0.0194,  1.0000]])