In [1]:
import numpy as np

L,d_k,d_v = 4,8,8

Q = np.random.randn(L,d_k)
K = np.random.randn(L,d_k)
V = np.random.randn(L,d_v)

Q,K,V


(array([[ 0.88751639,  0.02465853, -0.70810286, -0.24232136, -0.09200776,
          0.39901822,  0.17058618, -1.40259255],
        [ 0.04550906,  0.30190135, -1.10311813, -1.14134455, -0.12416257,
          0.53632591,  1.77300777, -0.06541501],
        [ 0.47509194,  0.09621482,  1.0234821 , -1.87393608,  1.28347078,
          0.05339085, -0.15562363, -0.30379203],
        [-0.50344714, -0.21771695,  0.23085562, -0.05584174, -0.6020663 ,
         -0.98262394,  1.29645715,  1.4779346 ]]),
 array([[ 0.07544902,  1.17633901, -0.00678408, -1.43392322, -0.1084998 ,
          0.11969405,  1.21236221, -1.0333617 ],
        [ 1.51012538,  1.06699039, -2.55425327,  0.2865979 ,  0.11460259,
         -1.99672161, -0.61730254, -0.63015006],
        [ 0.63218997, -0.94361824, -1.40679096, -0.57299392,  0.89974453,
          1.15469441, -0.05543782,  0.82730717],
        [-0.24005509,  1.17120406,  1.05313073,  0.25876268,  0.17402899,
         -1.22161928,  0.26885324,  0.94181282]]),
 array([[ 0.

#SELF ATTENTION

In [11]:
def self_attention(Q,K,V,mask):
  _n = np.matmul(Q,K.T)
  _d = np.sqrt(d_k)
  _f = _n/_d
  _f_ = _f + mask
  _f_ = softmax(_f_)
  return np.matmul(_f_,V)

def softmax(x):
  return np.exp(x)/np.sum(np.exp(x),axis=1,keepdims=True)

In [2]:
mask = np.tril(np.ones((L,L)))
mask

array([[1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 1.]])

In [8]:
for i in range(L):
  for j in range(L):
    if mask[i][j] == 0:
      mask[i][j] = (-np.infty)
    else:
      mask[i][j] = 0

"""
mask[mask==1] = 0
mask[mask==0] = -np.infty
"""

In [9]:
mask

array([[  0., -inf, -inf, -inf],
       [  0.,   0., -inf, -inf],
       [  0.,   0.,   0., -inf],
       [  0.,   0.,   0.,   0.]])

In [12]:
new_v = self_attention(Q,K,V,mask)

In [14]:
new_v,V

(array([[ 0.07369492,  0.44120076,  1.07965339, -0.06586887, -1.50646707,
         -0.19674951,  0.44863884, -1.11028124],
        [ 0.08322379,  0.48744153,  0.6568404 ,  0.05225543, -1.27975021,
          0.03359466,  0.43004977, -0.66817414],
        [ 0.09519635,  0.55725499,  1.12052661,  0.33038977, -1.45452838,
         -0.28445944,  0.22525499, -0.71206713],
        [ 0.30268804, -0.14796947, -0.47665018, -0.27487994, -0.69610233,
          0.56899549,  0.20663585, -0.18218493]]),
 array([[ 0.07369492,  0.44120076,  1.07965339, -0.06586887, -1.50646707,
         -0.19674951,  0.44863884, -1.11028124],
        [ 0.11670591,  0.6499204 , -0.82882211,  0.46731564, -0.48312206,
          0.84296832,  0.36473227,  0.88528323],
        [ 0.13093508,  0.75880009,  1.92270296,  1.08476203, -1.70740104,
         -0.87854806, -0.27994188, -0.49250288],
        [ 0.46132475, -0.74298756, -1.5242895 , -0.84897655, -0.21768939,
          1.13112802,  0.21775561, -0.02655661]]))